# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
      branches:
          - release

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2

    - name: install vue
      run: npm install @vue/cli

    - name: install firebase tools
      run: npm install firebase-tools

    - name: building vue
      run: npm run build

    - name: setup firebaseserc
      run: echo "{\"projects\":{\"default\" : \"${{ secrets.projectId }}\"}}" > .firebaseserc

    - name: deploy
      run: firebase deploy --token  ${{ secrets.firebaseToken }}